CREATE  TABLE   IF  NOT EXISTS  "tokens"
(
    id                                                  integer                                     GENERATED BY DEFAULT AS IDENTITY
,   uuid                                                uuid                            NOT NULL    DEFAULT gen_random_uuid ()
,   created_at                                          timestamp   with    time zone   NOT NULL    DEFAULT now()

,   CONSTRAINT  "PK_tokens"                             PRIMARY    KEY
    (
        id
    )
);

CREATE  TABLE   IF  NOT EXISTS  "bikes"
(
    id                                                  integer                                     GENERATED BY DEFAULT AS IDENTITY

,   CONSTRAINT  "PK_bikes"                              PRIMARY    KEY
    (
        id
    )
);

CREATE  TABLE   IF  NOT EXISTS  "bike_translatables"
(
    id                                                  integer                                     GENERATED BY DEFAULT AS IDENTITY
,   bike_id                                             integer                         NOT NULL
,   locale                                              varchar (    5 )                NOT NULL
,   title                                               varchar (  255 )                NOT NULL
,   "description"                                       text                                NULL
,   "url"                                               varchar ( 2048 )

,   CONSTRAINT  "PK_bike_translatables"                 PRIMARY    KEY
    (
        id
    )

,   CONSTRAINT  "UK_bike_translatables#bike_id#locale"  UNIQUE
    (
        bike_id
    ,   locale
    )

,   CONSTRAINT  "FK_bike_translatables_bikes"           FOREIGN KEY
    (
        bike_id
    )
    REFERENCES  "bikes"
    (
        id
    )
);

CREATE  TABLE   IF  NOT EXISTS  "rents"
(
    id                                                  integer                                     GENERATED BY DEFAULT AS IDENTITY
,   token_id                                            integer                         NOT NULL
,   bike_id                                             integer                         NOT NULL
,   created_at                                          timestamp   with    time zone   NOT NULL    DEFAULT now()
,   start_timestamp                                     timestamp   with    time zone   NOT NULL
,   end_timestamp                                       timestamp   with    time zone   NOT NULL
,   revocation_timestamp                                timestamp   with    time zone       NULL

,   CONSTRAINT  "PK_rents"                              PRIMARY KEY
    (
        id
    )

,   CONSTRAINT  "UK_rents#token_id"                     UNIQUE
    (
        token_id
    )

,   CONSTRAINT  "FK_rents_bikes"                        FOREIGN KEY
    (
        bike_id
    )
    REFERENCES  "bikes"
    (
        id
    )

,   CONSTRAINT  "FK_rents_tokens"                       FOREIGN KEY
    (
        token_id
    )
    REFERENCES  "tokens"
    (
        id
    )
);

CREATE  TABLE   IF  NOT EXISTS  "rent_details"
(
    id                                                  integer                                     GENERATED BY DEFAULT AS IDENTITY
,   rent_id                                             integer
,   encrypted_details                                   text                            NOT NULL

,   CONSTRAINT  "PK_rent_details"                       PRIMARY KEY
    (
        id
    )

,   CONSTRAINT  "FK_rent_details_rents"                 FOREIGN KEY
    (
        rent_id
    )
    REFERENCES  "rents"
    (
        id
    )
);

CREATE  TABLE   IF  NOT EXISTS  "token_challenges"
(
    id                                                  integer                                     GENERATED BY DEFAULT AS IDENTITY

,   CONSTRAINT  "PK_token_challenges"                   PRIMARY KEY
    (
        id
    )
);

CREATE  TABLE   IF  NOT EXISTS  "token_challenge_translatables"
(
    id                                                                          integer                                     GENERATED BY DEFAULT AS IDENTITY
,   token_challenge_id                                                          integer                         NOT NULL
,   locale                                                                      varchar (    5 )                NOT NULL
,   question                                                                    text                            NOT NULL
,   answer_hash                                                                 varchar (  128 )                NOT NULL
,   "url"                                                                       varchar ( 2048 )

,   CONSTRAINT  "PK_token_challenge_translatables"                              PRIMARY KEY
    (
        id
    )

,   CONSTRAINT  "UK_token_challenge_translatables#token_challenge_id@locale"    UNIQUE
    (
        token_challenge_id
    ,   locale
    )

,   CONSTRAINT  "FK_token_challenge_translatables_token_challenges"             FOREIGN KEY
    (
        token_challenge_id
    )
    REFERENCES  "token_challenges"
    (
        id
    )
);