CREATE  TABLE   IF  NOT EXISTS  "supporter_types"
(
    id                                                              integer                                     GENERATED BY DEFAULT AS IDENTITY
,   title                                                           varchar (  255 )                NOT NULL

,   CONSTRAINT  "PK_supporter_types"                                PRIMARY KEY
    (
        id
    )

,   CONSTRAINT  "UK_supporter_types#title"                          UNIQUE
    (
        title
    )
);

CREATE  TABLE   IF  NOT EXISTS  "supporters"
(
    id                                                              integer                                     GENERATED BY DEFAULT AS IDENTITY
,   supporter_type_id                                               integer

,   CONSTRAINT  "PK_supporters"                                     PRIMARY KEY
    (
        id
    )

,   CONSTRAINT  "FK_supporters_supporter_types"                     FOREIGN KEY
    (
        supporter_type_id
    )
    REFERENCES  "supporter_types"
    (
        id
    )
);

CREATE  TABLE   IF  NOT EXISTS  "supporter_translatables"
(
    id                                                              integer                                     GENERATED BY DEFAULT AS IDENTITY
,   supporter_id                                                    integer                         NOT NULL
,   locale                                                          varchar (    5 )                NOT NULL
,   title                                                           varchar (  255 )                NOT NULL
,   "description"                                                   text                                NULL
,   "url"                                                           varchar ( 2048 )                    NULL
,   logo_url                                                        varchar ( 2048 )                    NULL
,   logo_width                                                      smallint                            NULL
,   logo_height                                                     smallint                            NULL
,   logo_alt_text                                                   varchar (  100 )                    NULL

,   CONSTRAINT  "PK_supporter_translatables"                        PRIMARY KEY
    (
        id
    )

,   CONSTRAINT  "UK_supporter_translatables#supporter_id#locale"    UNIQUE
    (
        supporter_id
    ,   locale
    )

,   CONSTRAINT  "FK_supporter_translatables_supporters"             FOREIGN KEY
    (
        supporter_id
    )
    REFERENCES  "supporters"
    (
        id
    )
);